/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve */
        post: operations["retrieve_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["usage_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modes */
        get: operations["modes_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Availability
         * @description Liveness of a listing at its source, ORTHOGONAL to ``ingest_status``.
         *
         *     ``ingest_status`` tracks pipeline progress (discovered→raw→fresh→…); this
         *     axis tracks whether the source page still advertises the listing. Maintained
         *     solely by the Revisit stage (``seeker revisit``), never by ingest — so a
         *     listing can stay ``fresh`` + categorized while flipping to ``expired``.
         *
         *     ACTIVE:  assumed live at ingest; confirmed live by a revisit.
         *     EXPIRED: a revisit confirmed the source dropped the listing (OLX "gone"
         *              statusCode page / otodom ``/hpr/`` redirect). Terminal — an expired
         *              listing is never re-checked.
         *     UNKNOWN: a revisit could not confirm liveness for a transient reason (fetch
         *              failure / unparseable payload). Re-checked on every subsequent run
         *              until it resolves to active or expired.
         * @enum {string}
         */
        Availability: "active" | "expired" | "unknown";
        /**
         * CategorizationResult
         * @description Enrichment/facet blob persisted under `Listing.categorization`.
         *
         *     The categorize stage emits a DYNAMIC, YAML-driven schema
         *     (`config/inference_output.yml` → `StructuredOutputConfig.to_model`), so the
         *     fields stored here (design_style, condition, has_*, has_mezzanine, tags,
         *     description, …) are NOT enumerated on this model — it is a pure dynamic blob.
         *     `extra="allow"` keeps every field through a Listing round-trip — without it,
         *     reading a categorized Listing back from Mongo would silently drop every
         *     enrichment field, which the RAG stage depends on.
         *
         *     The text-derived cost/location values are NOT stored here — they are routed
         *     onto the canonical `cost_components` / `geo` / `base_location_text` fields by
         *     `build_categorization_writeback` (seeker/stages/categorize.py).
         */
        CategorizationResult: {
            [key: string]: unknown;
        };
        /**
         * CostComponents
         * @description Breakdown of monthly cost components.
         */
        CostComponents: {
            /** Rent */
            rent?: number | null;
            /** Admin Fee */
            admin_fee?: number | null;
            /** Utilities Estimated */
            utilities_estimated?: number | null;
        };
        /**
         * EmbeddingMeta
         * @description Tracking metadata for the Index stage (vector embedding).
         *
         *     The vector itself lives only in the vector store (keyed by ``listing_id`` =
         *     ``source_url``); Mongo keeps this lightweight marker. ``embedded_content_hash``
         *     is the staleness key: the Index pipeline re-embeds a listing whose composed
         *     text hash diverges from this value (re-categorised / edited), not just ones
         *     never embedded. ``embedding_recipe`` records the ordered components that
         *     produced that text (see ``EmbeddingRecipe``). ``index_backend`` records where
         *     the vector landed (e.g. ``"pgvector"``).
         */
        EmbeddingMeta: {
            /**
             * Embed Status
             * @default pending
             */
            embed_status: string;
            /** Embed Failure */
            embed_failure?: string | null;
            /** Embed Model */
            embed_model?: string | null;
            /** Embed Dimensions */
            embed_dimensions?: number | null;
            /** Embedded At */
            embedded_at?: string | null;
            /** Embedded Content Hash */
            embedded_content_hash?: string | null;
            embedding_recipe?: components["schemas"]["EmbeddingRecipe"] | null;
            /** Index Backend */
            index_backend?: string | null;
        };
        /**
         * EmbeddingRecipe
         * @description How the embedded chunk text was assembled — pointers, not values.
         *
         *     The ``embedded_content_hash`` proves *whether* the text changed; this records
         *     *what* went into it and *in what order*, without duplicating any
         *     categorization values. ``components`` is the ordered list of segment ids that
         *     contributed to the composed text: the static head segments are bare
         *     (``"title"`` / ``"description"`` / ``"location"``) and each categorization cue
         *     is ``"categorization.<field>"`` — a pointer back into
         *     ``details.categorization``. ``schema_version`` names the inference schema whose
         *     ``embed`` recipes render those pointers, so the exact text is reconstructable
         *     from ``(listing, schema_version)`` alone.
         */
        EmbeddingRecipe: {
            /** Schema Version */
            schema_version?: string | null;
            /** Components */
            components?: string[];
        };
        /**
         * FieldTarget
         * @description Where a field's value belongs in a /query or /retrieve request body.
         *
         *     ``location`` (serialized as ``in``): ``body`` => a top-level request field;
         *     ``facets`` => an entry in the request's ``facets`` map.
         */
        FieldTarget: {
            /** In */
            in: string;
            /** Name */
            name: string;
        };
        /**
         * FilterField
         * @description One filterable field, rendered generically by the frontend off ``type``.
         */
        FilterField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: number;
            /** Section */
            section: string;
            target: components["schemas"]["FieldTarget"];
            /** Modes */
            modes: string[];
            /** Options */
            options?: components["schemas"]["FilterOption"][] | null;
        };
        /**
         * FilterOption
         * @description One selectable value of a SELECT / MULTISELECT field.
         */
        FilterOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /**
         * FilterSchemaResponse
         * @description GET /filters payload: the ordered filter fields for one language.
         */
        FilterSchemaResponse: {
            /** Lang */
            lang: string;
            /** Fields */
            fields: components["schemas"]["FilterField"][];
        };
        /**
         * GeoFields
         * @description Structured geographic fields from Geocode stage.
         */
        GeoFields: {
            /** City */
            city?: string | null;
            /** District */
            district?: string | null;
            /** Street */
            street?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** @default pending */
            geocode_status: components["schemas"]["GeocodeStatus"];
            geocode_failure_category?: components["schemas"]["GeocodeFailureCategory"] | null;
        };
        /**
         * GeocodeFailureCategory
         * @description Reason a geo resolution ended in GeocodeStatus.FAILED.
         *
         *     Only meaningful when geocode_status is FAILED; None otherwise.
         *
         *     NO_SOURCE_LOCATION: the source provided nothing to geocode.
         *     UNRESOLVED:         the Geocode stage had text but could not resolve it.
         *     PROVIDER_ERROR:     the geocoding provider errored.
         * @enum {string}
         */
        GeocodeFailureCategory: "no_source_location" | "unresolved" | "provider_error";
        /**
         * GeocodeStatus
         * @description Lifecycle state of a listing's structured geo resolution.
         *
         *     PENDING:         awaiting the downstream Geocode stage (we hold
         *                      base_location_text but no coords yet).
         *     SOURCE_PROVIDED: coords came ready from the source payload — Geocode
         *                      stage may treat them as ground truth and skip resolution.
         *     SUCCESS:         Geocode stage resolved coords from the location text.
         *     FAILED:          terminal — either the source carried no location data at
         *                      all, or the Geocode stage could not resolve it. The reason
         *                      is carried by GeocodeFailureCategory.
         * @enum {string}
         */
        GeocodeStatus: "pending" | "source_provided" | "success" | "failed";
        /**
         * GraphMeta
         * @description Tracking metadata for the Graph-persist stage.
         */
        GraphMeta: {
            /**
             * Graph Status
             * @default pending
             */
            graph_status: string;
            /** Graph Persisted At */
            graph_persisted_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Listing
         * @description Canonical listing document in MongoDB.
         *
         *     Staged fill: metadata at fetch time (the heavy raw blob is archived
         *     separately in the ``raw_payloads`` collection), then normalized +
         *     categorized by subsequent pipeline stages.
         *
         *     The advertised-flat content & filterable parameters are grouped under
         *     ``details`` (see ``ListingDetails``); the top-level fields are pipeline /
         *     identity / provenance bookkeeping.
         */
        Listing: {
            /** Source Url */
            source_url: string;
            /** Source Adapter */
            source_adapter: string;
            /** Adapter Type */
            adapter_type: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Last Fetched At */
            last_fetched_at?: string | null;
            /** Ingest Status */
            ingest_status: string;
            /**
             * Image Fingerprints
             * @default []
             */
            image_fingerprints: string[];
            /** Duplicate Of */
            duplicate_of?: string | null;
            /** @default active */
            availability: components["schemas"]["Availability"];
            /** Last Checked At */
            last_checked_at?: string | null;
            /** Raw Payload Type */
            raw_payload_type?: string | null;
            /**
             * @default {
             *       "images": [],
             *       "cost_components": {},
             *       "cost_incomplete": true,
             *       "cost_components_missing": false,
             *       "geo": {
             *         "geocode_status": "pending"
             *       },
             *       "categorization": {}
             *     }
             */
            details: components["schemas"]["ListingDetails"];
            /**
             * Categorize Status
             * @default pending
             */
            categorize_status: string;
            /** Categorize Failure */
            categorize_failure?: string | null;
            /** Categorized At */
            categorized_at?: string | null;
            /** Categorization Prompt Version */
            categorization_prompt_version?: string | null;
            /**
             * @default {
             *       "embed_status": "pending"
             *     }
             */
            embedding: components["schemas"]["EmbeddingMeta"];
            /**
             * @default {
             *       "graph_status": "pending"
             *     }
             */
            graph: components["schemas"]["GraphMeta"];
            /** Pipeline Correlation Id */
            pipeline_correlation_id?: string | null;
            /** Selector Map Version */
            selector_map_version?: string | null;
            /** Adapter Version */
            adapter_version?: string | null;
            /**
             * Failures
             * @default []
             */
            failures: components["schemas"]["PipelineFailure"][];
            /** Failure Category */
            failure_category?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /** Failed Stage */
            failed_stage?: string | null;
            /** Failed At */
            failed_at?: string | null;
        };
        /**
         * ListingDetails
         * @description The listing's real-world content & filterable parameters.
         *
         *     Everything that describes the advertised flat itself — what the Normalize,
         *     Geocode and Categorize stages fill — lives here, deliberately split from the
         *     pipeline/identity bookkeeping on the parent ``Listing`` (ingest_status,
         *     *_version, embedding/graph markers, failures…). The split is purely
         *     structural: persisted under the ``details`` sub-document, every field keeps
         *     the same semantics it had when it was top-level.
         *
         *     Query/index paths therefore address these via ``details.`` (e.g.
         *     ``details.geo.city``, ``details.total_monthly_cost``,
         *     ``details.categorization.has_mezzanine``).
         */
        ListingDetails: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Area M2 */
            area_m2?: number | null;
            /** Rooms */
            rooms?: number | null;
            /** Floor */
            floor?: string | null;
            /** Building Type */
            building_type?: string | null;
            /** Elevator */
            elevator?: boolean | null;
            /** Furnished */
            furnished?: boolean | null;
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ListingImage"][];
            /** @default {} */
            cost_components: components["schemas"]["CostComponents"];
            /** Total Monthly Cost */
            total_monthly_cost?: number | null;
            /**
             * Cost Incomplete
             * @default true
             */
            cost_incomplete: boolean;
            /**
             * Cost Components Missing
             * @default false
             */
            cost_components_missing: boolean;
            /** Base Location Text */
            base_location_text?: string | null;
            /**
             * @default {
             *       "geocode_status": "pending"
             *     }
             */
            geo: components["schemas"]["GeoFields"];
            /** @default {} */
            categorization: components["schemas"]["CategorizationResult"];
        };
        /**
         * ListingImage
         * @description An image URL with an optional description added by a later enrichment step.
         */
        ListingImage: {
            /** Url */
            url: string;
            /** Description */
            description?: string | null;
        };
        /**
         * ModeCostProfile
         * @description What a search mode draws from the shared monthly budget.
         */
        ModeCostProfile: {
            /** Consumes Tokens */
            consumes_tokens: boolean;
            /** Consumes Request */
            consumes_request: boolean;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ModeInfo
         * @description One search mode (query / retrieve) and the fields it accepts.
         */
        ModeInfo: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Accepts */
            accepts: string[];
            cost_profile: components["schemas"]["ModeCostProfile"];
        };
        /**
         * ModesResponse
         * @description GET /modes payload: the modes plus the caller's current remaining quota.
         */
        ModesResponse: {
            /** Lang */
            lang: string;
            /** Modes */
            modes: components["schemas"]["ModeInfo"][];
            quota?: components["schemas"]["QuotaSnapshot"] | null;
        };
        /**
         * PipelineFailure
         * @description Structured failure record per Principle VIII.
         */
        PipelineFailure: {
            /** Stage */
            stage: string;
            /** Category */
            category: string;
            /** Message */
            message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * QueryRequest
         * @description Public query request with form-mode and prompt-mode options.
         */
        QueryRequest: {
            /** Prompt */
            prompt?: string | null;
            /** City */
            city?: string | null;
            /** District */
            district?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Radius Km */
            radius_km?: number | null;
            /** Max Cost */
            max_cost?: number | null;
            /**
             * Cost Mode
             * @default strict
             */
            cost_mode: string;
            /** Rooms */
            rooms?: number | null;
            /** Min Area */
            min_area?: number | null;
            /** Max Area */
            max_area?: number | null;
            /** Floor */
            floor?: string | null;
            /** Building Type */
            building_type?: string | null;
            /** Elevator */
            elevator?: boolean | null;
            /** Furnished */
            furnished?: boolean | null;
            /** Facets */
            facets?: {
                [key: string]: string;
            };
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /**
         * QueryResponse
         * @description Response to a query, with listings and availability status.
         */
        QueryResponse: {
            /** Listings */
            listings: components["schemas"]["Listing"][];
            /** Total Matched */
            total_matched: number;
            /** Source Availability */
            source_availability: {
                [key: string]: components["schemas"]["SourceStatus"];
            };
            /** Excluded Geocode Failed */
            excluded_geocode_failed: number;
            quota?: components["schemas"]["QuotaSnapshot"] | null;
        };
        /**
         * QuotaSnapshot
         * @description Current-period usage + remaining limits for the caller's tier.
         *
         *     Returned by GET /usage and GET /modes, and piggybacked on /query and /retrieve
         *     responses so the frontend updates the user's remaining quota without an extra
         *     round-trip. The token/request counters are the gating dimensions; ``spent_usd`` /
         *     ``spent_by_source`` are informational (display only). A ``None`` budget means that
         *     dimension is unlimited (premium tier).
         */
        QuotaSnapshot: {
            /** Tier */
            tier: string;
            /** Period */
            period: string;
            /** Request Count */
            request_count: number;
            /** Tokens Used */
            tokens_used: number;
            /** Token Budget */
            token_budget?: number | null;
            /** Remaining Tokens */
            remaining_tokens?: number | null;
            /** Request Budget */
            request_budget?: number | null;
            /** Remaining Requests */
            remaining_requests?: number | null;
            /** Rate Per Hour */
            rate_per_hour?: number | null;
            /** Max Tokens Per Request */
            max_tokens_per_request?: number | null;
            /**
             * Spent Usd
             * @default 0
             */
            spent_usd: number;
            /** Spent By Source */
            spent_by_source?: {
                [key: string]: number;
            };
        };
        /** RetrieveRequest */
        RetrieveRequest: {
            /** Query */
            query: string;
            /** City */
            city?: string | null;
            /** District */
            district?: string | null;
            /** Facets */
            facets?: {
                [key: string]: string;
            };
            /** Max Cost */
            max_cost?: number | null;
            /** K */
            k?: number | null;
            /**
             * Rerank
             * @default false
             */
            rerank: boolean;
        };
        /** RetrieveResponse */
        RetrieveResponse: {
            /** Results */
            results: components["schemas"]["ScoredListing"][];
            /** Total */
            total: number;
            quota?: components["schemas"]["QuotaSnapshot"] | null;
        };
        /** ScoredListing */
        ScoredListing: {
            /** Score */
            score: number;
            listing: components["schemas"]["Listing"];
        };
        /**
         * SourceStatus
         * @description Per-adapter availability and health status.
         */
        SourceStatus: {
            /** Available */
            available: boolean;
            /** Last Successful Reach At */
            last_successful_reach_at?: string | null;
            /** Message */
            message?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    retrieve_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    filters_filters_get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modes_modes_get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
