/**
 * Demo catalogue. Stands in for the query API until `GET /api/listings` and
 * `POST /api/chat` exist (both are still aspirational on the backend). Shapes
 * match the real Listing model so swapping in HttpClient calls is mechanical.
 */

import type { Listing } from '../models/listing.model';

function img(seed: string): { url: string; description: string } {
  return {
    url: `https://picsum.photos/seed/${seed}/960/640`,
    description: '',
  };
}

export const MOCK_LISTINGS: Listing[] = [
  {
    source_url: 'https://www.otodom.pl/pl/oferta/mokotow-bright-2room',
    source_adapter: 'otodom',
    title: 'Light-filled two-room near Pole Mokotowskie',
    description:
      'South-facing 2-room apartment with herringbone parquet, tall windows and a quiet balcony overlooking the park. Recently refreshed, fully furnished, separate kitchen.',
    area_m2: 48,
    rooms: 2,
    floor: 'floor_4',
    building_type: 'apartment',
    furnished: true,
    images: [img('mokotow-a'), img('mokotow-b'), img('mokotow-c')],
    cost_components: { rent: 3100, admin_fee: 380, utilities_estimated: 250 },
    total_monthly_cost: 3730,
    cost_incomplete: false,
    base_location_text: 'by the park, two tram stops to the centre',
    geo: { city: 'Warszawa', district: 'Mokotów', street: 'Wawelska' },
    enrichment: {
      design_style: 'scandinavian',
      condition: 'excellent',
      brightness: 'bright',
      flooring: 'wood-parquet',
      tags: ['herringbone parquet', 'south-facing', 'park view', 'quiet street'],
      has_balcony: 'yes',
      has_elevator: 'yes',
      has_furniture: 'yes',
      has_separate_kitchen: 'yes',
      has_dishwasher: 'yes',
      has_high_ceiling: 'yes',
    },
  },
  {
    source_url: 'https://www.olx.pl/oferta/srodmiescie-loft-studio',
    source_adapter: 'olx',
    title: 'Industrial studio in a converted Śródmieście tenement',
    description:
      'Open-plan loft with exposed brick, concrete floor and 3.4 m ceilings. Big factory windows, walk-in shower, washer and oven. Bare and characterful.',
    area_m2: 39,
    rooms: 1,
    floor: 'floor_2',
    building_type: 'tenement',
    furnished: false,
    images: [img('loft-a'), img('loft-b')],
    cost_components: { rent: 2700, admin_fee: 300, utilities_estimated: null },
    total_monthly_cost: null,
    cost_incomplete: true,
    base_location_text: 'central, near the metro',
    geo: { city: 'Warszawa', district: 'Śródmieście', street: 'Hoża' },
    enrichment: {
      design_style: 'industrial(loft)',
      condition: 'good',
      brightness: 'bright',
      flooring: 'concrete',
      tags: ['exposed brick', 'high ceilings', 'factory windows', 'open-plan'],
      has_balcony: 'no',
      has_elevator: 'no',
      has_furniture: 'no',
      has_walkin_shower: 'yes',
      has_washer_dryer: 'yes',
      has_high_ceiling: 'yes',
    },
  },
  {
    source_url: 'https://www.otodom.pl/pl/oferta/wilanow-family-three',
    source_adapter: 'otodom',
    title: 'Calm three-room with terrace in Wilanów',
    description:
      'Family-sized 3-room on a green estate. Modern kitchen with dishwasher, a wide terrace facing the garden, underground parking and a lift.',
    area_m2: 72,
    rooms: 3,
    floor: 'floor_1',
    building_type: 'apartment',
    furnished: true,
    images: [img('wilanow-a'), img('wilanow-b'), img('wilanow-c')],
    cost_components: { rent: 4200, admin_fee: 600, utilities_estimated: 350 },
    total_monthly_cost: 5150,
    cost_incomplete: false,
    base_location_text: 'quiet green estate, parking included',
    geo: { city: 'Warszawa', district: 'Wilanów', street: 'Klimczaka' },
    enrichment: {
      design_style: 'modern',
      condition: 'new',
      brightness: 'bright',
      flooring: 'laminate',
      tags: ['terrace', 'garden view', 'underground parking', 'gated estate'],
      has_terrace: 'yes',
      has_garden: 'yes',
      has_parking: 'yes',
      has_elevator: 'yes',
      has_dishwasher: 'yes',
      has_air_conditioning: 'yes',
    },
  },
  {
    source_url: 'https://www.olx.pl/oferta/praga-vintage-two',
    source_adapter: 'olx',
    title: 'Vintage two-room on the Praga side',
    description:
      'Pre-war flat with original double doors and tall ceilings, lightly worn. Tiled stove kept as a feature, small balcony, no lift. Lots of character for the price.',
    area_m2: 54,
    rooms: 2,
    floor: 'floor_3',
    building_type: 'tenement',
    furnished: true,
    images: [img('praga-a'), img('praga-b')],
    cost_components: { rent: 2400, admin_fee: 420, utilities_estimated: 280 },
    total_monthly_cost: 3100,
    cost_incomplete: false,
    base_location_text: 'arty, riverside district',
    geo: { city: 'Warszawa', district: 'Praga-Północ', street: 'Ząbkowska' },
    enrichment: {
      design_style: 'vintage',
      condition: 'fair',
      brightness: 'moderate',
      flooring: 'wood-parquet',
      tags: ['pre-war', 'tiled stove', 'high ceilings', 'character'],
      has_balcony: 'yes',
      has_elevator: 'no',
      has_furniture: 'yes',
      has_fireplace: 'yes',
      has_high_ceiling: 'yes',
    },
  },
  {
    source_url: 'https://www.otodom.pl/pl/oferta/wola-minimal-one',
    source_adapter: 'otodom',
    title: 'Minimalist one-room by Rondo Daszyńskiego',
    description:
      'Compact, bright studio in a new Wola tower. Built-in kitchen with induction hob and dishwasher, walk-in shower, air conditioning, gym and lift in the building.',
    area_m2: 31,
    rooms: 1,
    floor: 'floor_11',
    building_type: 'apartment',
    furnished: true,
    images: [img('wola-a'), img('wola-b')],
    cost_components: { rent: 3000, admin_fee: 500, utilities_estimated: 200 },
    total_monthly_cost: 3700,
    cost_incomplete: false,
    base_location_text: 'business district, metro at the door',
    geo: { city: 'Warszawa', district: 'Wola', street: 'Prosta' },
    enrichment: {
      design_style: 'minimalist',
      condition: 'new',
      brightness: 'bright',
      flooring: 'vinyl',
      tags: ['high floor', 'city view', 'new build', 'induction hob'],
      has_balcony: 'yes',
      has_elevator: 'yes',
      has_furniture: 'yes',
      has_air_conditioning: 'yes',
      has_dishwasher: 'yes',
      has_walkin_shower: 'yes',
    },
  },
  {
    source_url: 'https://www.olx.pl/oferta/zoliborz-classic-three',
    source_adapter: 'olx',
    title: 'Classic three-room off Plac Wilsona',
    description:
      'Elegant 3-room in a 1930s Żoliborz block. Restored parquet, separate kitchen, bathtub, leafy courtyard and a deep balcony. Furnished, lift in the stairwell.',
    area_m2: 68,
    rooms: 3,
    floor: 'floor_2',
    building_type: 'apartment',
    furnished: true,
    images: [img('zoliborz-a'), img('zoliborz-b'), img('zoliborz-c')],
    cost_components: { rent: 3900, admin_fee: 520, utilities_estimated: 300 },
    total_monthly_cost: 4720,
    cost_incomplete: false,
    base_location_text: 'leafy, well-connected, quiet courtyard',
    geo: { city: 'Warszawa', district: 'Żoliborz', street: 'Mickiewicza' },
    enrichment: {
      design_style: 'classic',
      condition: 'excellent',
      brightness: 'bright',
      flooring: 'wood-parquet',
      tags: ['1930s', 'restored parquet', 'courtyard', 'deep balcony'],
      has_balcony: 'yes',
      has_elevator: 'yes',
      has_furniture: 'yes',
      has_separate_kitchen: 'yes',
      has_bathtub: 'yes',
    },
  },
  {
    source_url: 'https://www.otodom.pl/pl/oferta/ursynow-boho-two',
    source_adapter: 'otodom',
    title: 'Boho two-room with a garden plot in Ursynów',
    description:
      'Ground-floor 2-room opening onto a private garden. Warm, layered interior, separate kitchen, washer and oven. Parking spot, no lift needed.',
    area_m2: 57,
    rooms: 2,
    floor: 'parter',
    building_type: 'apartment',
    furnished: true,
    images: [img('ursynow-a'), img('ursynow-b')],
    cost_components: { rent: 2900, admin_fee: 450, utilities_estimated: 260 },
    total_monthly_cost: 3610,
    cost_incomplete: false,
    base_location_text: 'green, residential, close to the forest',
    geo: { city: 'Warszawa', district: 'Ursynów', street: 'Jastrzębowskiego' },
    enrichment: {
      design_style: 'boho',
      condition: 'good',
      brightness: 'moderate',
      flooring: 'laminate',
      tags: ['private garden', 'ground floor', 'forest nearby', 'cosy'],
      has_garden: 'yes',
      has_parking: 'yes',
      has_furniture: 'yes',
      has_separate_kitchen: 'yes',
      has_washer_dryer: 'yes',
    },
  },
  {
    source_url: 'https://www.olx.pl/oferta/ochota-scandi-two',
    source_adapter: 'olx',
    title: 'Scandi two-room with a walk-in closet, Ochota',
    description:
      'Bright, pared-back 2-room with pale oak laminate, a walk-in closet and a glazed balcony. Dishwasher, washer, lift. Move-in ready and well kept.',
    area_m2: 50,
    rooms: 2,
    floor: 'floor_6',
    building_type: 'apartment',
    furnished: true,
    images: [img('ochota-a'), img('ochota-b')],
    cost_components: { rent: 3200, admin_fee: 410, utilities_estimated: 240 },
    total_monthly_cost: 3850,
    cost_incomplete: false,
    base_location_text: 'well-connected, near the university campus',
    geo: { city: 'Warszawa', district: 'Ochota', street: 'Grójecka' },
    enrichment: {
      design_style: 'scandinavian',
      condition: 'excellent',
      brightness: 'bright',
      flooring: 'laminate',
      tags: ['pale oak', 'walk-in closet', 'glazed balcony', 'move-in ready'],
      has_balcony: 'yes',
      has_elevator: 'yes',
      has_furniture: 'yes',
      has_walkin_closet: 'yes',
      has_dishwasher: 'yes',
      has_washer_dryer: 'yes',
    },
  },
];
